import * as React from 'react';
import {
  Formik,
  Form,
} from 'formik';
import { NextPage } from 'next';
import { Flex, Heading, VStack } from '@chakra-ui/layout';
import { Button } from '@chakra-ui/react';
import Head from 'next/head';
import Image from 'next/image';
import { InputField } from '../components/common/InputField';

interface MyFormValues {
  firstName: string;
  lastName: string;
  email: string
}

const CreateNewUserPage: NextPage = () => {

  const initValues: MyFormValues = {
    firstName: '',
    lastName: '',
    email: ''
  };

  const onSubmit = (values: MyFormValues) => {
    console.log({ values });

    alert(JSON.stringify(values, null, 2));
  }

  return (
    <Flex h="100vh" w="100vw" flexDirection="row">

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w="50%" h="full" alignItems="center" justifyContent="center">
        <Image width="640px" height="360px" src="/tsvsjs.jpg" />
      </Flex>

      <Flex w="50%" h="full" alignItems="center" justifyContent="center">

        <Formik
          initialValues={initValues}
          onSubmit={onSubmit}
        >
          <Form>
            <VStack>
              <Heading>Create new user</Heading>

              <InputField name='firstName' label='First name' />
              <InputField name='lastName' label='Last name' />
              <InputField name='email' label='Last name' type='email' />

              <Button type='submit'>Submit</Button>
            </VStack>
          </Form>
        </Formik>

      </Flex>
    </Flex>
  );
};

export default CreateNewUserPage;